//
// Created by okotcham on 12/11/2019.
//

#ifndef BATTLEARENA_DIRECTION_H
#define BATTLEARENA_DIRECTION_H

enum Direction{AVANCE,RECULE,TOURNER_GAUCHE,TOURNER_DROITE,TOURNER_CANON_GAUCHE,TOURNER_CANON_DROITE};

#endif //BATTLEARENA_DIRECTION_H
